@url = http://localhost:3610

### BASE
{{url}}

### ALL FLASHCARDS
{{url}}/flashcards

### ALL FLASHCARDS IN A CATEGORY
{{url}}/flashcards/category/git

### SINGLE FLASHCARD 
{{url}}/flashcards/2764

### SINGLE FLASHCARD: ERROR TEST NOT A NUMBER
{{url}}/flashcards/skjfksdfj

### SINGLE FLASHCARD: ERROR TEST ID OUT OF RANGE
{{url}}/flashcards/9999

### GET ALL CATEGORIES
{{url}}/categories
